version: "3.9"

services:

  telecom-api:

    build:
      context: ./backend

    container_name: telecom-api

    ports:
      - "8000:8000"

    volumes:
      - ./uploads:/uploads
      - ./extracted:/extracted
      - ./metadata:/metadata

    restart: unless-stopped
